[package]
name = "warframe"
version = "5.1.0"
edition = "2021"
description = "An async crate to wrap Warframe's Worldstate API."
readme = "./README.md"
documentation = "https://docs.rs/warframe"
homepage = "https://docs.rs/warframe"
repository = "https://github.com/Mettwasser/warframe.rs"
license = "MIT"


[features]
default = ["worldstate"]

worldstate = []
multilangual = ["worldstate"]
worldstate_listeners = ["worldstate"]
worldstate_full = ["worldstate", "multilangual", "worldstate_listeners"]
market = []
market_cache = ["market", "dep:moka"]
market_full = ["market", "market_cache"]

[dependencies]
tokio = { version = "1.34.0", features = ["full"] }
reqwest = { version = "0.12.5", features = ["json"] }
chrono = { version = "0.4.31", features = ["serde", "clock"] }
serde = { version = "1.0.190", features = ["derive"] }
serde_json = { version = "1.0.108" }
serde_repr = "0.1.18"
futures = "0.3.30"
log = "0.4.20"
env_logger = "0.11.1"
thiserror = "1.0.61"
moka = { version = "0.12.7", optional = true, features = ["future"] }
