[package]
name = "example-listener-object"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warframe = { path = "../../src", features = ["worldstate", "macros"]}
env_logger = "0.11.1"